name: Get YouTube Live m3u8
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
        #01 TaiwanPlus	
    - name: Get 01.m3u8
      run: |
        touch ./01.m3u8
        sudo cat >./01.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@TaiwanPlusLive/live)
        EOL
        # 09 大愛一台
    - name: Get 09.m3u8
      run: |
        touch ./09.m3u8
        sudo cat >./09.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=MIqUplvSRWA)
        EOL
        # 34 東森購物
    - name: Get 34.m3u8
      run: |
        touch ./34.m3u8
        sudo cat >./34.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=_Vlzn9qAHD4)
        EOL
        # 35 momo購物 2 台
    - name: Get 35.m3u8
      run: |
        touch ./35.m3u8
        sudo cat >./35.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=xbNWkUyxQGM)
        EOL    
        # 46 東森購物 3 台
    - name: Get 45.m3u8
      run: |
        touch ./45.m3u8
        sudo cat >./45.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Z50JFuNgvB0)
        EOL	
          # 46 東森購物 1 台
    - name: Get 46.m3u8
      run: |
        touch ./46.m3u8
        sudo cat >./46.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=ViJ3XiN6Q3M)
        EOL	  
        # 47 momo購物 1 台
    - name: Get 47.m3u8
      run: |
        touch ./47.m3u8
        sudo cat >./47.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=_pZQ1Lk0xMA)
        EOL
        # 52 中天新聞
    - name: Get 52.m3u8
      run: |
        touch ./52.m3u8
        sudo cat >./52.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=oIgbl7t0S_w)
        EOL	  
        # 53 民視新聞台
    - name: Get 53.m3u8
      run: |
        touch ./53.m3u8
        sudo cat >./53.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=ylYJSBUgaMA)
        EOL	 
        # 54 三立新聞
    - name: Get 54.m3u8
      run: |
        touch ./54.m3u8
        sudo cat >./54.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=oZdzzvxTfUY)
        EOL
        # 57 東森財經新聞
    - name: Get 57.m3u8
      run: |
        touch ./57.m3u8
        sudo cat >./57.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=WHEPzbFA3hw)
        EOL	  
        # 59 viva購物 1 台
    - name: Get 59.m3u8
      run: |
        touch ./59.m3u8
        sudo cat >./59.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=yuhgIlXwPh8)
        EOL	  
        # 60 東森購物 5 台
    - name: Get 60.m3u8
      run: |
        touch ./60.m3u8
        sudo cat >./60.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=u0NYyH3ZesE)
        EOL
        # 85 寰宇新聞台
    - name: Get 85.m3u8
      run: |
        touch ./85.m3u8
        sudo cat >./85.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=B7Zp3d6xXWw)
        EOL
        # 86 鏡電視新聞台
    - name: Get 86.m3u8
      run: |
        touch ./86.m3u8
        sudo cat >./85.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=5n0y6b0Q25o)
        EOL
        # 91 幸福空間居家台
    - name: Get 91.m3u8
      run: |
        touch ./91.m3u8
        sudo cat >./91.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=_jbDwrcm0Xw)
        EOL	  
        # 92 運通財經台
    - name: Get 92.m3u8
      run: |
        touch ./92.m3u8
        sudo cat >./92.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=bqxeU38_25Y)
        EOL	  
        # 93 全球財經台
    - name: Get 93.m3u8
      run: |
        touch ./93.m3u8
        sudo cat >./93.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=3aDnRkAOhqc)
        EOL	  
        # 94 誠心電視台
    - name: Get 94.m3u8
      run: |
        touch ./94.m3u8
        sudo cat >./94.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=_K5ouJ10O5Y)
        EOL	  
        # 98 海豚綜合台
    - name: Get 98.m3u8
      run: |
        touch ./98.m3u8
        sudo cat >./98.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=0jS0tyzaMLE)
        EOL
        # 103 十方法界電視台
    - name: Get 103.m3u8
      run: |
        touch ./103.m3u8
        sudo cat >./103.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Yw4gKhWcGN8)
        EOL	 
        # 106 信大電視台
    - name: Get 106.m3u8
      run: |
        touch ./106.m3u8
        sudo cat >./106.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=AQymzwl3uSk)
        EOL	 
        # 109 正德電視台
    - name: Get 109.m3u8
      run: |
        touch ./109.m3u8
        sudo cat >./109.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=CHDb5D0DCkw)
        EOL	 
        # 116 三聖電視台
    - name: Get 116.m3u8
      run: |
        touch ./116.m3u8
        sudo cat >./116.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=KLIVRxVzBO4)
        EOL	 
        # 154 中視新聞
    - name: Get 154.m3u8
      run: |
        touch ./154.m3u8
        sudo cat >./154.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=TCnaIE_SAtM)
        EOL	 
        # 155 台視新聞
    - name: Get 155.m3u8
      run: |
        touch ./155.m3u8
        sudo cat >./155.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=xL0ch83RAK8)
        EOL	 
        # 297 大愛二台
    - name: Get 297.m3u8
      run: |
        touch ./297.m3u8
        sudo cat >./297.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=DTNkEm6jaqQ)
        EOL
        # 397 viva購物 2 台
    - name: Get 397.m3u8
      run: |
        touch ./397.m3u8
        sudo cat >./397.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=LEOat38Iuao)
        EOL	
        # 552 Bloomberg 財經
    - name: Get 552.m3u8
      run: |
        touch ./552.m3u8
        sudo cat >./552.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=LEOat38Iuao)
        EOL		
        # 554 CNBC News
    - name: Get 554.m3u8
      run: |
        touch ./554.m3u8
        sudo cat >./554.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=9NyxcX3rhQs)
        EOL		
        # 561 Al Jazeera(半島電視)
    - name: Get 561.m3u8
      run: |
        touch ./561.m3u8
        sudo cat >./561.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=gCNeDWCI0vo)
        EOL		
        # MOMO親子台 哈婆婆故事屋
    - name: Get momo1.m3u8
      run: |
        touch ./momo1.m3u8
        sudo cat >./momo1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=LgbuqiPNz_g)
        EOL		
        # MOMO親子台 M O M O這一家S2
    - name: Get momo2.m3u8
      run: |
        touch ./momo2.m3u8
        sudo cat >./momo2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=IiAAXnxEocc)
        EOL		
        # MOMO親子台 歡樂谷 
    - name: Get momo3.m3u8
      run: |
        touch ./momo3.m3u8
        sudo cat >./momo3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=eJu0PrOu-2g)
        EOL		
        # 綜藝玩很大
    - name: Get a01.m3u8
      run: |
        touch ./a01.m3u8
        sudo cat >./a01.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=pD67r3WKnUY)
        EOL		
        # 天才衝衝衝
    - name: Get a02.m3u8
      run: |
        touch ./a02.m3u8
        sudo cat >./a02.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=8lhgX90zz1M)
        EOL		
        # 飢餓遊戲
    - name: Get a03.m3u8
      run: |
        touch ./a03.m3u8
        sudo cat >./a03.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=3xe-R00ijC4)
        EOL		
        # 台灣誌
    - name: Get a04.m3u8
      run: |
        touch ./a04.m3u8
        sudo cat >./a04.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=fmy-HVZtqBY)
        EOL		
        # 小明星大跟班
    - name: Get a05.m3u8
      run: |
        touch ./a05.m3u8
        sudo cat >./a05.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=gvRVJ6oNl_A)
        EOL		
        # 萬秀豬王
    - name: Get a06.m3u8
      run: |
        touch ./a06.m3u8
        sudo cat >./a06.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=ADDSmXoPDY8)
        EOL		
        # 豬哥會社
    - name: Get a07.m3u8
      run: |
        touch ./a07.m3u8
        sudo cat >./a07.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=htGDPsz2BYI)
        EOL		
        # 新兵日記
    - name: Get a08.m3u8
      run: |
        touch ./a08.m3u8
        sudo cat >./a08.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=bn7glmBPmIQ)
        EOL		
        # 命中註定我愛你
    - name: Get a09.m3u8
      run: |
        touch ./a09.m3u8
        sudo cat >./a09.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=W2kcQcQ7MIM)
        EOL		
        # 兩個爸爸
    - name: Get a10.m3u8
      run: |
        touch ./a10.m3u8
        sudo cat >./a10.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=n5UOsjtRr6Y)
        EOL		
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
