name: Get YouTube Live m3u8
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
        #01 TaiwanPlus	
    - name: Get 01.m3u8
      run: |
        touch ./01.m3u8
        sudo cat >./01.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@TaiwanPlusLive/live)
        EOL
        # 34 東森購物
    - name: Get 34.m3u8
      run: |
        touch ./34.m3u8
        sudo cat >./34.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=_Vlzn9qAHD4)
        EOL
        # 35 momo購物 2 台
    - name: Get 35.m3u8
      run: |
        touch ./35.m3u8
        sudo cat >./35.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=xbNWkUyxQGM)
        EOL    
        # 46 東森購物 3 台
    - name: Get 46.m3u8
      run: |
        touch ./46.m3u8
        sudo cat >./46.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Z50JFuNgvB0)
        EOL	
          # 47 東森購物 1 台
    - name: Get 47.m3u8
      run: |
        touch ./47.m3u8
        sudo cat >./47.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=ViJ3XiN6Q3M)
        EOL	  
        # 48 momo購物 1 台
    - name: Get 48.m3u8
      run: |
        touch ./48.m3u8
        sudo cat >./48.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=_pZQ1Lk0xMA)
        EOL
        # 52 中天新聞
    - name: Get 52.m3u8
      run: |
        touch ./52.m3u8
        sudo cat >./52.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=oIgbl7t0S_w)
        EOL	  
        # 53 民視新聞台
    - name: Get 53.m3u8
      run: |
        touch ./53.m3u8
        sudo cat >./53.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=ylYJSBUgaMA)
        EOL	  
        # 57 東森財經新聞
    - name: Get 57.m3u8
      run: |
        touch ./57.m3u8
        sudo cat >./57.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=WHEPzbFA3hw)
        EOL	  
        # 59 viva購物 1 台
    - name: Get 59.m3u8
      run: |
        touch ./59.m3u8
        sudo cat >./59.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=yuhgIlXwPh8)
        EOL	  
        # 60 東森購物 5 台
    - name: Get 60.m3u8
      run: |
        touch ./60.m3u8
        sudo cat >./60.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=u0NYyH3ZesE)
        EOL	         
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
